# Generated by Django 2.0 on 2019-02-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='nome',
            field=models.CharField(default='Base', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
