# Generated by Django 2.1 on 2018-09-17 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0009_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta_Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField(default=datetime.date.today)),
                ('data_liquidacao', models.DateField()),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Acao')),
            ],
            options={
                'verbose_name_plural': 'Boletas de operação de ações',
            },
        ),
    ]
