# Generated by Django 2.1 on 2018-09-20 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0010_auto_20180920_1714'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fundo', '0005_auto_20180918_1607'),
        ('boletagem', '0002_boleta_acao_corretora'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField(default=datetime.date.today)),
                ('data_liquidacao', models.DateField()),
                ('operacao', models.CharField(choices=[('C', 'C'), ('V', 'V')], max_length=1, verbose_name='Compra/Venda')),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=7, max_digits=13)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Acao')),
                ('caixa_alvo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Caixa')),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Corretora')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
            options={
                'verbose_name_plural': 'Boletas de operação de ações',
            },
        ),
        migrations.CreateModel(
            name='BoletaCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.DecimalField(decimal_places=6, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('financeiro_origem', models.DecimalField(decimal_places=6, max_digits=16)),
                ('financeiro_final', models.DecimalField(decimal_places=6, max_digits=16)),
                ('data_liquidacao_origem', models.DateField(default=datetime.date.today)),
                ('data_liquidacao_destino', models.DateField(default=datetime.date.today)),
                ('caixa_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_caixa_final', to='ativos.Caixa')),
                ('caixa_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_caixa_origem', to='ativos.Caixa')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaCPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('valor_cheio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_inicio', models.DateField()),
                ('data_vigencia_inicio', models.DateField(blank=True, null=True)),
                ('data_vigencia_fim', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaEmprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField(default=datetime.date.today)),
                ('data_vencimento', models.DateField()),
                ('data_liquidacao', models.DateField()),
                ('reversivel', models.BooleanField()),
                ('data_reversao', models.DateField()),
                ('operacao', models.CharField(max_length=10, verbose_name='Operação')),
                ('comissao', models.DecimalField(decimal_places=6, max_digits=9)),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=6, max_digits=8)),
                ('preco', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Acao')),
                ('boleta_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletagem.BoletaEmprestimo')),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Corretora')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaFundoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField(default=datetime.date.today)),
                ('data_cotizacao', models.DateField()),
                ('data_liquidacao', models.DateField()),
                ('operacao', models.CharField(choices=[('Aplicação', 'Aplicação'), ('Resgate', 'Resgate'), ('Resgate Total', 'Resgate Total')], max_length=13)),
                ('liquidacao', models.CharField(choices=[('Interna', 'Interna'), ('Transferência', 'Transferência'), ('CETIP', 'CETIP')], max_length=13)),
                ('financeiro', models.DecimalField(decimal_places=6, max_digits=16)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Fundo_Local')),
                ('caixa_alvo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Caixa')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaFundoOffshore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=48)),
                ('data_operacao', models.DateField()),
                ('data_cotizacao', models.DateField()),
                ('data_liquidacao', models.DateField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Fundo_Offshore')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaPrecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaProvisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('financeiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('object_id', models.PositiveIntegerField()),
                ('caixa_alvo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Caixa')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaRendaFixaLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField(default=datetime.date.today)),
                ('data_liquidacao', models.DateField(default=datetime.date.today)),
                ('operacao', models.CharField(choices=[('C', 'C'), ('V', 'V')], max_length=1, verbose_name='Compra/Venda')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=6, max_digits=13)),
                ('taxa', models.DecimalField(decimal_places=4, max_digits=6)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Renda_Fixa')),
                ('caixa_alvo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Caixa')),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Corretora')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaRendaFixaOffshore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateField(default=datetime.date.today)),
                ('data_liquidacao', models.DateField(default=datetime.date.today)),
                ('operacao', models.CharField(choices=[('C', 'C'), ('V', 'V')], max_length=1, verbose_name='Compra/Venda')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal', models.DecimalField(decimal_places=6, max_digits=13)),
                ('taxa', models.DecimalField(decimal_places=4, max_digits=6)),
                ('preco', models.DecimalField(decimal_places=8, max_digits=10)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Renda_Fixa')),
                ('caixa_alvo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Caixa')),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Corretora')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.RemoveField(
            model_name='boleta_acao',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='boleta_acao',
            name='corretora',
        ),
        migrations.DeleteModel(
            name='Boleta_Acao',
        ),
    ]
