# Generated by Django 2.1 on 2018-09-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0003_auto_20180920_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletacpr',
            options={'verbose_name_plural': 'Boletas de CPR'},
        ),
    ]
