# Generated by Django 2.1 on 2018-09-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0005_auto_20180921_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaprovisao',
            name='descricao',
            field=models.CharField(default='Operação', max_length=50, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
