# Generated by Django 2.1 on 2018-09-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0011_auto_20180924_1129'),
        ('boletagem', '0007_boletacpr_fundo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletaprovisao',
            options={'verbose_name_plural': 'Boletas de provisão'},
        ),
        migrations.AddField(
            model_name='boletaemprestimo',
            name='caixa_alvo',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, to='ativos.Caixa'),
            preserve_default=False,
        ),
    ]
