# Generated by Django 2.1 on 2018-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0008_auto_20180924_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletaemprestimo',
            options={'verbose_name_plural': 'Boletas de Empréstimo'},
        ),
        migrations.AlterField(
            model_name='boletaemprestimo',
            name='operacao',
            field=models.CharField(choices=[('Doador', 'Doador'), ('Tomador', 'Tomador')], max_length=10, verbose_name='Operação'),
        ),
    ]
