# Generated by Django 2.1 on 2018-09-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
        ('boletagem', '0009_auto_20180924_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaemprestimo',
            name='calendario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='calendario.Calendario'),
            preserve_default=False,
        ),
    ]
