# Generated by Django 2.1 on 2018-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0010_boletaemprestimo_calendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaemprestimo',
            name='data_liquidacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boletaemprestimo',
            name='data_reversao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
