# Generated by Django 2.1 on 2018-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0011_auto_20180925_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaemprestimo',
            name='quantidade',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
