# Generated by Django 2.1 on 2018-09-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0012_auto_20180925_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaemprestimo',
            name='boleta_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boletagem.BoletaEmprestimo'),
        ),
    ]
