# Generated by Django 2.1 on 2018-09-26 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0011_auto_20180924_1129'),
        ('boletagem', '0013_auto_20180925_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaPassivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='boletaprecos',
            name='data',
            field=models.DateField(default=datetime.date(2018, 9, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletaprecos',
            name='preco',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='boletaprecos',
            unique_together={('ativo', 'data')},
        ),
    ]
