# Generated by Django 2.0 on 2018-10-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0014_auto_20180926_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletarendafixalocal',
            name='data_liquidacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
