# Generated by Django 2.0 on 2018-10-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0016_auto_20181004_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletacpr',
            old_name='valor_parcial',
            new_name='valor_diario',
        ),
    ]
