# Generated by Django 2.0 on 2018-10-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0017_auto_20181005_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaacao',
            name='corretagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
