# Generated by Django 2.0 on 2018-10-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0019_boletarendafixalocal_corretagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletarendafixaoffshore',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='boletarendafixaoffshore',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='boletarendafixaoffshore',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='boletarendafixaoffshore',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
