# Generated by Django 2.0 on 2018-10-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0020_auto_20181011_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletarendafixaoffshore',
            name='corretagem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
