# Generated by Django 2.0 on 2018-10-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0021_boletarendafixaoffshore_corretagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletafundolocal',
            name='financeiro',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='boletafundolocal',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='boletafundolocal',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
