# Generated by Django 2.0 on 2018-10-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0011_auto_20180924_1129'),
        ('boletagem', '0023_boletaacao_custodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletafundooffshore',
            name='caixa_alvo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ativos.Caixa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletafundooffshore',
            name='financeiro',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='boletafundooffshore',
            name='operacao',
            field=models.CharField(choices=[('Aplicação', 'Aplicação'), ('Resgate', 'Resgate'), ('Resgate Total', 'Resgate Total')], default='Aplicação', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletafundooffshore',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='boletafundooffshore',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='boletafundooffshore',
            name='estado',
            field=models.CharField(choices=[('Pendente de Cotização', 'Pendente de Cotização'), ('Pendente de Liquidação', 'Pendente de Liquidação'), ('Pendente de informação de Cotização', 'Pendente de informação de Cotização'), ('Pendente de Liquidação e informação de Cotização', 'Pendente de Liquidação e informação de Cotização'), ('Pendente de Liquidação e Cotização', 'Pendente de Liquidação e Cotização'), ('Concluído', 'Concluído')], max_length=48),
        ),
    ]
