# Generated by Django 2.0 on 2018-10-16 21:32

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0011_auto_20180924_1129'),
        ('boletagem', '0024_auto_20181016_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletaprecos',
            old_name='data',
            new_name='data_referencia',
        ),
        migrations.AddField(
            model_name='boletaprecos',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletaprecos',
            name='preco_contabil',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='boletaprecos',
            name='preco_fechamento',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='boletaprecos',
            name='preco_gerencial',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.RemoveField(
            model_name='boletaprecos',
            name='preco',
        ),
        migrations.AlterUniqueTogether(
            name='boletaprecos',
            unique_together={('ativo', 'data_referencia')},
        ),
    ]
