# Generated by Django 2.0 on 2018-10-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0026_auto_20181017_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletafundooffshore',
            name='fechada',
            field=models.BooleanField(default=False),
        ),
    ]
