# Generated by Django 2.0 on 2018-10-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0028_auto_20181018_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletafundooffshore',
            name='fechada',
        ),
    ]
