# Generated by Django 2.0 on 2018-10-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0029_remove_boletafundooffshore_fechada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boletaprecos',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='boletaprecos',
            name='ativo',
        ),
        migrations.DeleteModel(
            name='BoletaPrecos',
        ),
    ]
