# Generated by Django 2.0 on 2018-10-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0030_auto_20181018_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacpr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boletaprovisao',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='boletaprovisao',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
