# Generated by Django 2.0 on 2018-10-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0031_auto_20181019_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacpr',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
