# Generated by Django 2.0 on 2018-10-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0034_auto_20181019_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletapassivo',
            old_name='boleta_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='boletapassivo',
            old_name='boleta_id',
            new_name='object_id',
        ),
    ]
