# Generated by Django 2.0 on 2018-10-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0035_auto_20181019_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletapassivo',
            name='operacao',
            field=models.CharField(choices=[('Aplicação', 'Aplicação'), ('Resgate', 'Resgate'), ('Resgate Total', 'Resgate Total')], default='Aplicação', max_length=15),
            preserve_default=False,
        ),
    ]
