# Generated by Django 2.0 on 2018-10-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0036_boletapassivo_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapassivo',
            name='cota',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
