# Generated by Django 2.0 on 2018-10-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0018_auto_20181019_1625'),
        ('boletagem', '0037_auto_20181019_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletafundooffshore',
            name='fundo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo'),
            preserve_default=False,
        ),
    ]
