# Generated by Django 2.0 on 2018-10-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0039_auto_20181023_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletafundooffshore',
            name='estado',
            field=models.CharField(choices=[('Pendente de Cotização', 'Pendente de Cotização'), ('Pendente de Liquidação', 'Pendente de Liquidação'), ('Pendente de informação de Cotização', 'Pendente de informação de Cotização'), ('Pendente de Liquidação e informação de Cotização', 'Pendente de Liquidação e informação de Cotização'), ('Pendente de Liquidação e Cotização', 'Pendente de Liquidação e Cotização'), ('Concluído', 'Concluído')], max_length=80),
        ),
    ]
