# Generated by Django 2.0 on 2018-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0040_auto_20181023_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacpr',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
