# Generated by Django 2.0 on 2018-10-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0042_boletaprovisao_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletacpr',
            old_name='valor_diario',
            new_name='valor_parcial',
        ),
        migrations.AddField(
            model_name='boletacpr',
            name='capitalizacao',
            field=models.CharField(choices=[('Diária', 'Diária'), ('Mensal', 'Mensal')], default='Diário', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletacpr',
            name='tipo',
            field=models.CharField(choices=[('Diarização', 'Diarização'), ('Diferimento', 'Diferimento'), ('CPR', 'CPR')], default='CPR', max_length=11),
            preserve_default=False,
        ),
    ]
