# Generated by Django 2.0 on 2018-10-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0045_auto_20181026_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletapassivo',
            name='fundo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo'),
        ),
    ]
