# Generated by Django 2.0 on 2018-10-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0022_remove_certificadopassivo_boleta_passivo'),
        ('boletagem', '0046_auto_20181029_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletapassivo',
            name='certificado_passivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo.CertificadoPassivo'),
        ),
    ]
