# Generated by Django 2.0 on 2018-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0024_auto_20181029_1709'),
        ('boletagem', '0047_boletapassivo_certificado_passivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletapassivo',
            name='certificado_passivo',
        ),
        migrations.AddField(
            model_name='boletapassivo',
            name='certificado_passivo',
            field=models.ManyToManyField(blank=True, null=True, to='fundo.CertificadoPassivo'),
        ),
    ]
