# Generated by Django 2.0 on 2018-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0048_auto_20181029_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaprovisao',
            name='financeiro',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
