# Generated by Django 2.0 on 2018-10-30 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0049_auto_20181030_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletacambio',
            name='data_operacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
