# Generated by Django 2.0 on 2018-11-01 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0050_boletacambio_data_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacpr',
            name='data_pagamento',
            field=models.DateField(blank=True, default=datetime.date(9999, 12, 31), null=True),
        ),
        migrations.AlterField(
            model_name='boletacpr',
            name='tipo',
            field=models.CharField(choices=[('Acúmulo', 'Acúmulo'), ('Diferimento', 'Diferimento'), ('CPR', 'CPR'), ('Empréstimo', 'Empréstimo')], default='CPR', max_length=12),
        ),
    ]
