# Generated by Django 2.0 on 2018-11-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0029_auto_20181108_1100'),
        ('boletagem', '0052_auto_20181101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaemprestimo',
            name='custodia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletafundolocal',
            name='custodia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletafundooffshore',
            name='custodia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletarendafixalocal',
            name='custodia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletarendafixaoffshore',
            name='custodia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante'),
            preserve_default=False,
        ),
    ]
