# Generated by Django 2.0 on 2018-11-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0053_auto_20181108_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletapassivo',
            old_name='data_movimentacao',
            new_name='data_operacao',
        ),
    ]
