# Generated by Django 2.0 on 2018-12-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0054_auto_20181129_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacpr',
            name='tipo',
            field=models.CharField(choices=[('Acúmulo', 'Acúmulo'), ('Diferimento', 'Diferimento'), ('CPR', 'CPR'), ('Empréstimo', 'Empréstimo'), ('Taxa de administração', 'Taxa de administração')], default='CPR', max_length=12),
        ),
    ]
