# Generated by Django 2.0 on 2018-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0055_auto_20181205_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletafundolocal',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='boletapassivo',
            name='cota',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
