# Generated by Django 2.0 on 2018-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0056_auto_20181211_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletacpr',
            name='tipo',
            field=models.CharField(choices=[('Acúmulo', 'Acúmulo'), ('Diferimento', 'Diferimento'), ('CPR', 'CPR'), ('Empréstimo', 'Empréstimo'), ('Taxa de administração', 'Taxa de administração')], default='CPR', max_length=21),
        ),
    ]
