# Generated by Django 2.0 on 2019-02-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0057_auto_20181211_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaprovisao',
            name='estado',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Liquidado', 'Liquidado'), ('Zeragem', 'Zeragem')], default='Pendente', max_length=9),
        ),
    ]
