# Generated by Django 2.1.1 on 2018-09-06 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ativos', '0001_squashed_0002_moeda_codigo'), ('ativos', '0002_auto_20180905_1642'), ('ativos', '0003_auto_20180905_1751'), ('ativos', '0004_auto_20180905_1856'), ('ativos', '0005_auto_20180906_1006')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Moeda')),
            ],
        ),
        migrations.CreateModel(
            name='Renda_Fixa',
            fields=[
                ('vencimento', models.DateField(default=datetime.date(9999, 12, 31))),
                ('cupom', models.DecimalField(decimal_places=5, default=0, max_digits=7, null=True)),
                ('info', models.CharField(choices=[('PU', 'PU'), ('YLD', 'Yield')], default='PU', max_length=3, verbose_name='informacao de mercado')),
                ('periodo', models.IntegerField(default=0, verbose_name='periodicidade do cupom')),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='moeda',
            name='codigo',
            field=models.CharField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('tipo', models.CharField(choices=[('PN', 'Preferencial'), ('ON', 'Ordinária')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
                ('bbg_ticker', models.CharField(max_length=25, null=True, unique=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ativos.Pais')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='acao',
            name='ativo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renda_fixa',
            name='ativo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo'),
            preserve_default=False,
        ),
    ]
