# Generated by Django 2.1.1 on 2018-09-06 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
                ('bbg_ticker', models.CharField(max_length=25, null=True, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Moeda')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo')),
                ('tipo', models.CharField(choices=[('PN', 'Preferencial'), ('ON', 'Ordinária')], max_length=20, null=True)),
            ],
            bases=('ativos.ativo',),
        ),
        migrations.CreateModel(
            name='Renda_Fixa',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo')),
                ('vencimento', models.DateField(default=datetime.date(9999, 12, 31))),
                ('cupom', models.DecimalField(decimal_places=5, default=0, max_digits=7, null=True)),
                ('info', models.CharField(choices=[('PU', 'PU'), ('YLD', 'Yield')], default='PU', max_length=3, verbose_name='informacao de mercado')),
                ('periodo', models.IntegerField(default=0, verbose_name='periodicidade do cupom')),
            ],
            bases=('ativos.ativo',),
        ),
        migrations.AddField(
            model_name='ativo',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ativos.Pais'),
        ),
    ]
