# Generated by Django 2.1.1 on 2018-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moeda',
            name='codigo',
            field=models.CharField(default=1, max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
