# Generated by Django 2.1.1 on 2018-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_squashed_0002_moeda_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda_fixa',
            name='tipo_ativo',
            field=models.CharField(choices=[('RV', 'Renda Variável'), ('RF', 'Renda Fixa'), ('RE', 'Real Estate'), ('FRV', 'Fundo de Renda Variável'), ('FRF', 'Fundo de Renda Fixa'), ('FII', 'Fundo Imobiliário')], default='RV', max_length=5),
        ),
    ]
