# Generated by Django 2.1.1 on 2018-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_squashed_0005_auto_20180906_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='renda_fixa',
            options={},
        ),
    ]
