# Generated by Django 2.1 on 2018-09-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_auto_20180911_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo')),
                ('moeda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_moeda_destino', to='ativos.Moeda')),
                ('moeda_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambio_moeda_origem', to='ativos.Moeda')),
            ],
            options={
                'verbose_name_plural': 'Câmbios',
            },
            bases=('ativos.ativo',),
        ),
    ]
