# Generated by Django 2.1.1 on 2018-09-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_auto_20180905_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
                ('bbg_ticker', models.CharField(max_length=25, null=True, unique=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ativos.Pais')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='acao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='renda_fixa',
            options={},
        ),
        migrations.RemoveField(
            model_name='acao',
            name='bbg_ticker',
        ),
        migrations.RemoveField(
            model_name='acao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='acao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='acao',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='renda_fixa',
            name='bbg_ticker',
        ),
        migrations.RemoveField(
            model_name='renda_fixa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='renda_fixa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='renda_fixa',
            name='pais',
        ),
        migrations.AddField(
            model_name='acao',
            name='ativo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renda_fixa',
            name='ativo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo'),
            preserve_default=False,
        ),
    ]
