# Generated by Django 2.1 on 2018-09-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0008_auto_20180914_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo')),
                ('zeragem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='ativos.Ativo')),
            ],
            options={
                'verbose_name_plural': 'Caixas',
            },
            bases=('ativos.ativo',),
        ),
    ]
