# Generated by Django 2.1 on 2018-09-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0009_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundo_Local',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo')),
                ('CPNJ', models.CharField(max_length=18)),
                ('data_cotizacao_resgate', models.DateField()),
                ('data_liquidacao_resgate', models.DateField()),
                ('data_cotizacao_aplicacao', models.DateField()),
                ('data_liquidacao_aplicacao', models.DateField()),
                ('banco', models.CharField(blank=True, max_length=3, null=True)),
                ('agencia', models.CharField(blank=True, max_length=6, null=True)),
                ('conta_corrente', models.CharField(max_length=7)),
                ('digito', models.CharField(blank=True, max_length=1, null=True)),
                ('conta_cetip', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_cetip', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fundos Locais',
            },
            bases=('ativos.ativo',),
        ),
        migrations.CreateModel(
            name='Fundo_Offshore',
            fields=[
                ('ativo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ativos.Ativo')),
            ],
            options={
                'verbose_name_plural': 'Fundos Offshore',
            },
            bases=('ativos.ativo',),
        ),
        migrations.AddField(
            model_name='ativo',
            name='isin',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='moeda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ativos.Moeda'),
            preserve_default=False,
        ),
    ]
