# Generated by Django 2.0 on 2018-10-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0012_cpr_fundo'),
        ('ativos', '0011_auto_20180924_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='custodia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante'),
            preserve_default=False,
        ),
    ]
