# Generated by Django 2.0 on 2018-10-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0013_auto_20181018_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo_local',
            name='gerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo'),
        ),
    ]
