# Generated by Django 2.0 on 2018-10-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0014_auto_20181018_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundo_local',
            name='data_cotizacao_aplicacao',
        ),
        migrations.AddField(
            model_name='fundo_local',
            name='data_cotizacao_aplicacao',
            field=models.DurationField(),
        ),
        migrations.RemoveField(
            model_name='fundo_local',
            name='data_cotizacao_resgate',
        ),
        migrations.AddField(
            model_name='fundo_local',
            name='data_cotizacao_resgate',
            field=models.DurationField(),
        ),
        migrations.RemoveField(
            model_name='fundo_local',
            name='data_liquidacao_aplicacao',
        ),
        migrations.AddField(
            model_name='fundo_local',
            name='data_liquidacao_aplicacao',
            field=models.DurationField(),
        ),
        migrations.RemoveField(
            model_name='fundo_local',
            name='data_liquidacao_resgate',
        ),
        migrations.AddField(
            model_name='fundo_local',
            name='data_liquidacao_resgate',
            field=models.DurationField(),
        ),
        migrations.RemoveField(
            model_name='fundo_offshore',
            name='data_cotizacao_aplicacao',
        ),
        migrations.AddField(
            model_name='fundo_offshore',
            name='data_cotizacao_aplicacao',
            field=models.DurationField(),
        ),
        migrations.RemoveField(
            model_name='fundo_offshore',
            name='data_cotizacao_resgate',
        ),
        migrations.AddField(
            model_name='fundo_offshore',
            name='data_cotizacao_resgate',
            field=models.DurationField(),
        ),
        migrations.RemoveField(
            model_name='fundo_offshore',
            name='data_liquidacao_aplicacao',
        ),
        migrations.AddField(
            model_name='fundo_offshore',
            name='data_liquidacao_aplicacao',
            field=models.DurationField(),
        ),
        migrations.RemoveField(
            model_name='fundo_offshore',
            name='data_liquidacao_resgate',
        ),
        migrations.AddField(
            model_name='fundo_offshore',
            name='data_liquidacao_resgate',
            field=models.DurationField(),
        ),
    ]
