# Generated by Django 2.0 on 2018-10-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0015_auto_20181018_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundo_local',
            old_name='gerido',
            new_name='gestao',
        ),
    ]
