# Generated by Django 2.0 on 2018-10-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0020_auto_20181026_1504'),
        ('ativos', '0016_auto_20181018_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundo_offshore',
            name='gerido',
        ),
        migrations.AddField(
            model_name='fundo_offshore',
            name='gestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo'),
        ),
    ]
