# Generated by Django 2.0 on 2018-10-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0017_auto_20181026_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
