# Generated by Django 2.0 on 2018-11-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0019_caixa_corretora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo_local',
            name='CPNJ',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='fundo_local',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
