# Generated by Django 2.0 on 2018-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0022_auto_20181205_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo_offshore',
            name='data_cotizacao_aplicacao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundo_offshore',
            name='data_cotizacao_resgate',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundo_offshore',
            name='data_liquidacao_aplicacao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundo_offshore',
            name='data_liquidacao_resgate',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
