# Generated by Django 2.0 on 2018-12-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0023_auto_20181211_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda_fixa',
            name='info',
            field=models.CharField(choices=[('PU', 'PU'), ('Yield', 'Yield')], default='PU', max_length=5, verbose_name='informação de mercado'),
        ),
    ]
