# Generated by Django 2.0 on 2018-12-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0024_auto_20181211_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo_local',
            name='data_cotizacao_aplicacao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundo_local',
            name='data_cotizacao_resgate',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundo_local',
            name='data_liquidacao_aplicacao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundo_local',
            name='data_liquidacao_resgate',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
