# Generated by Django 2.0 on 2018-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0025_auto_20181217_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='nome',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
