# Generated by Django 2.0 on 2019-02-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0026_auto_20181217_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='tipo',
            field=models.CharField(choices=[('PN', 'PN'), ('ON', 'ON'), ('ADR', 'ADR')], max_length=20, null=True),
        ),
    ]
