# Generated by Django 2.0 on 2019-02-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0027_auto_20190204_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='zeragem',
        ),
    ]
