# Generated by Django 2.0 on 2019-02-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0028_remove_caixa_zeragem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='tipo',
            field=models.CharField(choices=[('PN', 'PN'), ('ON', 'ON'), ('ADR', 'ADR'), ('Unit', 'Unit'), ('Direito de Subscrição', 'Direito de Subscrição'), ('Recibo de Subscrição', 'Recibo de Subscrição')], max_length=21, null=True),
        ),
    ]
