# Generated by Django 2.0 on 2018-10-18 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0013_auto_20181018_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_referencia', models.DateField()),
                ('preco_fechamento', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('preco_contabil', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('preco_gerencial', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('preco_estimado', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Ativo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='preco',
            unique_together={('ativo', 'data_referencia')},
        ),
    ]
