# Generated by Django 2.0 on 2018-11-01 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0018_ativo_descricao'),
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_declaracao', models.DateField(blank=True, null=True)),
                ('data_ex', models.DateField()),
                ('data_pagamento', models.DateField(default=datetime.date(9999, 12, 31))),
                ('tipo_provento', models.CharField(choices=[('Dividendo', 'Dividendo'), ('Juros sobre Capital Próprio', 'Juros sobre Capital Próprio'), ('Stock Split', 'Stock Split'), ('Direitos de Subscrição', 'Direitos de Subscrição'), ('Bonificação de Ações', 'Bonificação de Ações')], max_length=27)),
                ('valor_bruto', models.DecimalField(decimal_places=9, max_digits=18)),
                ('direito_por_acao', models.DecimalField(decimal_places=9, max_digits=11)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
