# Generated by Django 2.0 on 2018-11-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_auto_20181107_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provento',
            name='tipo_provento',
            field=models.CharField(choices=[('Dividendo', 'Dividendo'), ('Juros sobre Capital Próprio', 'Juros sobre Capital Próprio'), ('Stock Split/Inplit', 'Stock Split/Inplit'), ('Direitos de Subscrição', 'Direitos de Subscrição'), ('Bonificação de Ações', 'Bonificação de Ações')], max_length=27),
        ),
    ]
