# Generated by Django 2.0 on 2019-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_auto_20181211_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='provento',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
