# Generated by Django 2.0 on 2019-02-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_provento_valor_liquido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provento',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Acao'),
        ),
    ]
