# Generated by Django 2.1 on 2018-09-17 18:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0009_caixa'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Administradoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(max_length=20)),
                ('observacao', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('taxa_fixa', models.DecimalField(decimal_places=5, default=0, max_digits=7, null=True)),
                ('taxa_minima', models.DecimalField(decimal_places=5, default=0, max_digits=7, null=True)),
                ('taxa_corretagem', models.DecimalField(decimal_places=7, default=0, max_digits=9, null=True)),
                ('emolumentos', models.DecimalField(decimal_places=7, default=0, max_digits=9, null=True)),
                ('corretagem_por_acao', models.DecimalField(decimal_places=7, default=0, max_digits=9, null=True)),
                ('rebate', models.DecimalField(decimal_places=7, default=0, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Corretoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Distribuidora',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('Fundo de Ações', 'Fundo de Ações'), ('Fundo Multimercado', 'Fundo Multimercado'), ('Fundo Imobiliário', 'Fundo Imobiliário'), ('Fundo de Renda Fixa', 'Fundo de Renda Fixa')], max_length=40, null=True, verbose_name='Categoria do Fundo')),
                ('data_de_inicio', models.DateField(null=True)),
                ('taxa_administracao', models.DecimalField(decimal_places=5, max_digits=7)),
                ('capitalizacao_taxa_adm', models.CharField(choices=[('Diária', 'Diária'), ('Mensal', 'Mensal')], max_length=15)),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Administradora')),
                ('distribuidora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo.Distribuidora')),
            ],
            options={
                'verbose_name_plural': 'Fundos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Gestora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Gestoras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='fundo',
            name='gestora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Gestora'),
        ),
        migrations.AddField(
            model_name='fundo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Pais'),
        ),
    ]
