# Generated by Django 2.1 on 2018-09-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0009_caixa'),
        ('fundo', '0004_auto_20180918_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cota', models.DecimalField(decimal_places=6, max_digits=15)),
                ('ativos', models.ManyToManyField(to='ativos.Ativo')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'fundo'), ('model', 'administradora')), models.Q(('app_label', 'fundo'), ('model', 'corretora')), models.Q(('app_label', 'fundo'), ('model', 'distribuidora')), models.Q(('app_label', 'fundo'), ('model', 'gestora')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
