# Generated by Django 2.1 on 2018-09-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0010_auto_20180920_1714'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fundo', '0005_auto_20180918_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasamentoVerticeMovimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CasamentoVerticeQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cotista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Custodiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Custodiantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=20)),
                ('data', models.DateField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='Quantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=20)),
                ('data', models.DateField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
        ),
        migrations.CreateModel(
            name='Vertice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=20)),
                ('preco', models.DecimalField(decimal_places=6, max_digits=20)),
                ('movimentacao', models.DecimalField(decimal_places=6, max_digits=20)),
                ('data', models.DateField()),
                ('object_id', models.PositiveIntegerField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.Ativo')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('custodia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo')),
            ],
            options={
                'verbose_name_plural': 'Vértices',
                'ordering': ['fundo'],
            },
        ),
        migrations.AlterModelOptions(
            name='carteira',
            options={'ordering': ['fundo'], 'verbose_name_plural': 'Carteira'},
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='ativos',
        ),
        migrations.AddField(
            model_name='casamentoverticequantidade',
            name='quantidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Quantidade'),
        ),
        migrations.AddField(
            model_name='casamentoverticequantidade',
            name='vertice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Vertice'),
        ),
        migrations.AddField(
            model_name='casamentoverticemovimentacao',
            name='quantidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Quantidade'),
        ),
        migrations.AddField(
            model_name='casamentoverticemovimentacao',
            name='vertice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Vertice'),
        ),
        migrations.AddField(
            model_name='carteira',
            name='vertices',
            field=models.ManyToManyField(to='fundo.Vertice'),
        ),
    ]
