# Generated by Django 2.1 on 2018-09-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0006_auto_20180920_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casamentoverticemovimentacao',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='casamentoverticemovimentacao',
            name='movimentacao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='fundo.Movimentacao'),
            preserve_default=False,
        ),
    ]
