# Generated by Django 2.1 on 2018-09-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0007_auto_20180921_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertice',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='vertice',
            name='object_id',
        ),
    ]
