# Generated by Django 2.0 on 2018-10-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boletagem', '0028_auto_20181018_1341'),
        ('fundo', '0013_auto_20181018_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoPassivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_cotas', models.DecimalField(decimal_places=7, max_digits=15)),
                ('valor_cota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotas_aplicadas', models.DecimalField(decimal_places=7, max_digits=15)),
                ('boleta_passivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletagem.BoletaPassivo')),
            ],
        ),
        migrations.RenameField(
            model_name='gestora',
            old_name='local',
            new_name='anima',
        ),
        migrations.AddField(
            model_name='cotista',
            name='cota_media',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotista',
            name='n_doc',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotista',
            name='nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificadopassivo',
            name='cotista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fundo.Cotista'),
        ),
    ]
