# Generated by Django 2.0 on 2018-10-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0014_auto_20181018_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotista',
            name='n_doc',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cotista',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
