# Generated by Django 2.0 on 2018-10-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0015_auto_20181019_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotista',
            name='cota_media',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True),
        ),
    ]
