# Generated by Django 2.0 on 2018-10-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0016_auto_20181019_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotista',
            name='fundo_cotista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo'),
        ),
        migrations.AlterField(
            model_name='cotista',
            name='n_doc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
