# Generated by Django 2.0 on 2018-10-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0020_auto_20181026_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotista',
            name='fundo_cotista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo', unique=True),
        ),
    ]
