# Generated by Django 2.0 on 2018-10-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0021_auto_20181026_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadopassivo',
            name='boleta_passivo',
        ),
    ]
