# Generated by Django 2.0 on 2018-10-29 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0022_remove_certificadopassivo_boleta_passivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadopassivo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
