# Generated by Django 2.0 on 2018-10-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0023_certificadopassivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadopassivo',
            name='data',
            field=models.DateField(),
        ),
    ]
