# Generated by Django 2.0 on 2018-10-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0024_auto_20181029_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpr',
            old_name='descricao',
            new_name='nome',
        ),
    ]
