# Generated by Django 2.0 on 2018-11-01 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0025_auto_20181030_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fundo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundo',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpr',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
