# Generated by Django 2.0 on 2018-11-08 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0028_fundo_calendario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertice',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='vertice',
            name='movimentacao',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
    ]
