# Generated by Django 2.0 on 2018-11-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0029_auto_20181108_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='custodia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo.Custodiante'),
        ),
        migrations.AlterField(
            model_name='vertice',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
