# Generated by Django 2.0 on 2018-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0030_auto_20181108_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadopassivo',
            name='valor_cota',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
