# Generated by Django 2.0 on 2018-12-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0032_vertice_corretora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cpr',
            name='fundo',
        ),
        migrations.AlterField(
            model_name='fundo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Fundo de Ações', 'Fundo de Ações'), ('Fundo Multimercado', 'Fundo Multimercado'), ('Fundo Imobiliário', 'Fundo Imobiliário'), ('Fundo de Renda Fixa', 'Fundo de Renda Fixa'), ('Fundo de Participações', 'Fundo de Participações')], max_length=40, null=True, verbose_name='Categoria do Fundo'),
        ),
        migrations.DeleteModel(
            name='CPR',
        ),
    ]
