# Generated by Django 2.0 on 2018-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0033_auto_20181205_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='data_exercicio_social',
            field=models.DateField(blank=True, null=True),
        ),
    ]
