# Generated by Django 2.0 on 2018-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0035_vertice_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='pl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
