# Generated by Django 2.0 on 2018-12-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0036_carteira_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='taxa_adm_minima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Taxa de Administração Mínima'),
        ),
    ]
