# Generated by Django 2.0 on 2018-12-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0037_fundo_taxa_adm_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='movimentacao',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificadopassivo',
            name='fundo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fundo.Fundo'),
            preserve_default=False,
        ),
    ]
