# Generated by Django 2.0 on 2018-12-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo', '0038_auto_20181214_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundo',
            name='btg_id',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='ib_id',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='jefferies_id',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='xp_id',
        ),
        migrations.AlterField(
            model_name='carteira',
            name='cota',
            field=models.DecimalField(decimal_places=8, max_digits=17),
        ),
    ]
