# Generated by Django 2.0 on 2019-02-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0027_auto_20190204_1049'),
        ('fundo', '0041_auto_20190206_1036'),
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigZeragem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_zeragem_caixa', to='ativos.Caixa')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundo.Fundo')),
                ('indice_zeragem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_zeragem_indice_zeragem', to='ativos.Ativo')),
            ],
        ),
    ]
